export const ADD_CITY      = '@@ADD_CITY'
export const DELETE_CITY   = '@@DELETE_CITY'
export const SORT_BY_CITY  = '@@SORT_BY_CITY'
export const PENDING       = '/PENDING'
export const SUCCESS       = '/SUCCESS'
export const FAILURE       = '/FAILURE'